# Generated by Django 2.2.4 on 2019-08-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grkhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmembers',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
