# Generated by Django 2.2.4 on 2019-08-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grkhome', '0002_auto_20190808_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmembers',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
