# Generated by Django 2.2.4 on 2019-08-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grkhome', '0003_auto_20190808_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_first_name', models.CharField(max_length=50, null=True)),
                ('applicant_last_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AllMembers',
        ),
    ]
