# Generated by Django 2.2.4 on 2019-08-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grkhome', '0004_auto_20190809_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregister',
            name='applicant_ca_homeNumber',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='applicant_company',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='applicant_mobile',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='applicant_occupation',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='ca_pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='ca_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='ca_street_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='in_conatctNumber',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='in_homeNumber',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='in_pincode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='in_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberregister',
            name='in_street_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
